# Generated by Django 2.2.2 on 2019-08-09 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Art & Crafts', 'Art & Crafts'), ('Baby', 'Baby'), ('Beauty & Personal care', 'Beauty & Personal care'), ('Books', 'Books'), ('Computers', 'Computers'), ('Electronics', 'Electronics'), ('6', "Women's Fashion"), ('7', "Men's Fashion"), ('8', "Girl's Fashion"), ('9', "Boys's Fashion"), ('10', 'Home & Kitchen'), ('11', 'Others')], max_length=50),
        ),
    ]
