# Generated by Django 2.2.2 on 2019-08-09 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20190809_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Art & Crafts', 'Art & Crafts'), ('Baby', 'Baby'), ('Beauty & Personal care', 'Beauty & Personal care'), ('Books', 'Books'), ('Computers', 'Computers'), ('Electronics', 'Electronics'), ("Women's Fashion", "Women's Fashion"), ("Men's Fashion", "Men's Fashion"), ("Girl's Fashion", "Girl's Fashion"), ("Boys's Fashion", "Boys's Fashion"), ('Home & Kitchen', 'Home & Kitchen'), ('Others', 'Others')], max_length=50),
        ),
    ]
